apiVersion: v1
kind: Service
metadata:
  name: k8s-go-app-srv
  labels: 
    app: statics
spec:
  type: NodePort
  ports:
    - name: http
      port: 9090
      targetPort: 8080
      protocol: TCP
  selector:
    app: k8s-go-app